# Generated by Django 2.1 on 2018-08-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='training',
            field=models.ManyToManyField(to='WorkforceManagement.Training_Prog'),
        ),
    ]
