# Generated by Django 2.0.6 on 2018-08-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_Prog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_name', models.CharField(max_length=50)),
                ('training_desc', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('max_attendance', models.CharField(max_length=50)),
            ],
        ),
    ]
